# This is only used for local development environment
version: '3.3'
services:
  partitions-app:
    container_name: nim-game-app
    image: postgres:15.2-alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nim-game-app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  test-nestjs-adminer:
    image: adminer
    container_name: nim-game-app-adminer
    ports:
      - 8181:8080
    environment:
      - ADMINER_DEFAULT_SERVER=nim-game-app
